### ISSUE TITLE
git pull error

### ISSUE THREAD

**Issue by isovector** [isovector/take2#39]
```
Oops, cannot start the server.
org.eclipse.jgit.api.errors.InvalidConfigurationException: No value for key branch.master.merge found in configuration
        at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:173)
        at models.GitModel$class.update(GitModel.scala:44)
        at models.RepoModel$.update(RepoModel.scala:55)
        at models.GitModel$class.initialize(GitModel.scala:35)
        at models.RepoModel$.initialize(RepoModel.scala:55)
        at Global$.onStart(Global.scala:7)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:203)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
        at play.api.Play$.start(Play.scala:87)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:52)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:243)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:279)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:274)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:274)
        at play.core.server.NettyServer.main(NettyServer.scala)
```

**Comment by isovector** [comment]
GitModel#setBranch has config generation that should fix this
