### ISSUE TITLE
Issue when closing vim

### ISSUE THREAD

**Issue by MatthewMaclean** [isovector/take2#40]
Error detected while processing function recording#onExit:
line    6:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 1551, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1546, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process

**Comment by isovector** [comment]
probably don't have accio installed. shitty error for that tho!
